spring.application.name=BookInventory

spring.datasource.url=jdbc:mysql://localhost:3306/bookdb
spring.datasource.username=root
spring.datasource.password=nipun

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


